[target.x86_64-unknown-linux-musl]
image = "ghcr.io/cross-rs/x86_64-unknown-linux-musl:main"

[target.aarch64-unknown-linux-musl]
image = "ghcr.io/cross-rs/aarch64-unknown-linux-musl:main"

[target.x86_64-apple-darwin]
image = "x86_64-apple-darwin-cross:local"

[target.aarch64-apple-darwin]
image = "aarch64-apple-darwin-cross:local"
