---
name: Sync fork with upstream Repository

on:
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *"

permissions:
  contents: write
  actions: read 

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Sync master via Fork-Sync action
        uses: aormsby/Fork-Sync-With-Upstream-action@v3.4.1
        with:
          target_sync_branch: master
          target_repo_token: ${{ secrets.WORKFLOW_SYNC }}
          upstream_sync_repo: euzu/tuliprox
          upstream_sync_branch: master

      - name: Sync develop via Fork-Sync action
        uses: aormsby/Fork-Sync-With-Upstream-action@v3.4.1
        with:
          target_sync_branch: develop
          target_repo_token: ${{ secrets.WORKFLOW_SYNC }}
          upstream_sync_repo: euzu/tuliprox
          upstream_sync_branch: develop

